// F1-71 forensic evidence generator: "The robot that reboots when it drives off".
// Runs the power model of power_model.h as the robot was built: the MCU board is
// fed after the shared motor wire, and the motors get full duty at once.
// The log is synthetic, generated by the model; values are pretend.
#include "power_model.h"

int main()
{
    PowerConfig asBuilt;
    simulatePower(asBuilt);
    return 0;
}
