#!/usr/bin/env bash
# F4-30 run.sh: DR402's arch-neutral code (F4-23 neutral_tests.cc + F3-18 kformat/kprint/panic/
# cxxrt, compiled unchanged) built with clang for ten CPUs and run as a Linux user program under
# qemu-user. Three rounds:
#   1. first try: the kernel flags only, nothing added per CPU  -> what breaks at build time
#   2. ported:    per-CPU flags and port32.cc where needed       -> what breaks at run time
#   3. fixed:     the 32-bit CPUs again, with neutral_fix.py's copies of the two shared files
# Then the forensic evidence (qemu-user -strace of the 32-bit crash).
set -u -o pipefail
cd "$(dirname "$0")"
. ../F4-23/dlab.sh
status=0
CLANG_VER="$(clang++ --version | head -n 1); $(ld.lld --version | head -n 1)"
QUSER_VER="$(qemu-x86_64 --version | head -n 1)"
SCR="$(pwd)/.scratch"                       # removed at the end; never outside this folder
mkdir -p "$SCR"

# name | clang target | qemu-user binary | flags round 2 | port file round 2
TARGETS="x86_64|x86_64-linux-gnu|qemu-x86_64||
i386|i686-linux-gnu|qemu-i386||port32.cc
aarch64|aarch64-linux-gnu|qemu-aarch64|-mno-outline-atomics|
arm|armv7a-linux-gnueabihf|qemu-arm||port32.cc
riscv64|riscv64-linux-gnu|qemu-riscv64||
riscv32|riscv32-linux-gnu|qemu-riscv32|-Wno-atomic-alignment|port32.cc
loongarch64|loongarch64-linux-gnu|qemu-loongarch64||
mips|mips-linux-gnu|qemu-mips|-Wno-atomic-alignment|port32.cc
ppc|powerpc-linux-gnu|qemu-ppc|-Wno-atomic-alignment|port32.cc
s390x|s390x-linux-gnu|qemu-s390x||"
CFLAGS="-std=c++20 -ffreestanding -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-stack-protector \
-fno-pic -fno-pie -O2 -Wall -Wextra -Werror -nostdinc++"

# the devicetree the tests parse (F4-27's make_dtb.py) as a C++ array
python3 - "$SCR/dtb_blob.h" <<'EOF'
import sys
sys.dont_write_bytecode = True
sys.path.insert(0, "../F4-27")
import make_dtb
d = make_dtb.build()
with open(sys.argv[1], "w") as f:
    f.write("// generated by F4-30/run.sh from F4-27/make_dtb.py\n#pragma once\n#include <cstdint>\n")
    f.write("alignas(8) inline constexpr uint8_t kDtbBlobBytes[%d] = {\n" % len(d))
    for i in range(0, len(d), 16):
        f.write("    " + ", ".join("0x%02x" % b for b in d[i:i + 16]) + ",\n")
    f.write("};\ninline const void* const kDtbBlob = kDtbBlobBytes;\n")
EOF

# ubuild <name> <target> <flags> <extra sources> <header dir>: compile + link into $SCR/<name>/t.
# The F3-18 .cc files are copied next to the headers they should see (as dlab.sh kbuild does),
# so that their #include "arch.h" finds F4-30's arch.h. Prints the first error, if any.
ubuild() {
    local name="$1" tgt="$2" flags="$3" extra="$4" hdr="$5"
    local o="$SCR/$name" s
    mkdir -p "$o"
    rm -f "$o"/*.o "$o/t" "$o/err.txt"
    for s in ustart.cc "$hdr/neutral_tests.cc" "$hdr/kprint.cc" "$hdr/panic.cc" "$hdr/cxxrt.cc" $extra; do
        clang++ --target="$tgt" $CFLAGS $flags -DARCH_NAME="\"$name\"" -I"$hdr" -Ifsinc -I. -I"$SCR" -I../F4-23 \
            -c "$s" -o "$o/$(basename "$s").o" > "$o/err.txt" 2>&1 || {
            grep -m 1 'error' "$o/err.txt" | sed "s#$(pwd)/##g; s#$SCR/##g; s#$LABS/#labs/#g"
            return 1
        }
    done
    ld.lld -static -nostdlib -T user.ld -o "$o/t" "$o"/*.o > "$o/err.txt" 2>&1 || {
        grep -m 1 'error' "$o/err.txt" | sed "s#$SCR/[a-z0-9_]*/##g"
        return 1
    }
}
# header dirs: "orig" = byte-for-byte copies; "fixed" = neutral_fix.py's copies
mkdir -p "$SCR/orig" "$SCR/fixed"
for f in kformat.h kprint.h serial.h panic.h kprint.cc panic.cc cxxrt.cc; do
    cp "../F3-18/$f" "$SCR/orig/$f"
    cp "../F3-18/$f" "$SCR/fixed/$f"
done
cp ../F4-23/neutral_tests.cc "$SCR/orig/"
python3 neutral_fix.py "$LABS" "$SCR/fixed" > fix.out 2>&1; rc=$?
rec fix "neutral_fix.py (writes fixed copies; prints the diff)" "$(python3 --version)" \
    "python3 neutral_fix.py labs .scratch/fixed" "$rc"
[ "$rc" = 0 ] || status=1

# 1. first try: no per-CPU help at all
{
    printf '%-12s %s\n' "CPU" "result of compile + link with the kernel flags only"
    echo "$TARGETS" | while IFS='|' read -r name tgt q fl port; do
        if err="$(ubuild "$name" "$tgt" "" "" "$SCR/orig")"; then
            printf '%-12s %s\n' "$name" "built"
        else
            printf '%-12s %s\n' "$name" "FAILED: $err"
        fi
    done
} > first_try.out 2>&1
rec first_try "ustart.cc + neutral_tests.cc + F3-18 files, ten CPUs" "$CLANG_VER" \
    "clang++ --target=<cpu> $CFLAGS -c ...; ld.lld -T user.ld" "0" \
    "result:    some builds failed as expected (the table in first_try.out is the evidence)"
[ "$(grep -c FAILED first_try.out)" -ge 1 ] || status=1

# 2. ported: per-CPU flags and port32.cc; then run each under qemu-user
run_round() {   # run_round <outfile> <header dir> <names...>
    local out="$1" hdr="$2"
    shift 2
    {
        printf '%-12s %-6s %-5s %s\n' "CPU" "build" "exit" "summary line (or the last line printed)"
        echo "$TARGETS" | while IFS='|' read -r name tgt q fl port; do
            case " $* " in *" $name "*) ;; *) continue ;; esac
            if ! err="$(ubuild "$name" "$tgt" "$fl" "$port" "$hdr")"; then
                printf '%-12s %-6s %-5s %s\n' "$name" "FAIL" "-" "$err"
                continue
            fi
            ( timeout 20 "$q" "$SCR/$name/t" > "$SCR/$name/run.txt" 2>&1 ) 2> /dev/null
            local rc=$?
            local last; last="$(grep -a 'passed,' "$SCR/$name/run.txt" || tail -n 2 "$SCR/$name/run.txt" | tr '\n' ' ')"
            printf '%-12s %-6s %-5s %s\n' "$name" "ok" "$rc" "$last"
        done
        echo
        echo "== full output on two CPUs: s390x (big-endian, 64-bit) and arm (little-endian, 32-bit) =="
        for n in s390x arm; do
            [ -f "$SCR/$n/run.txt" ] && { echo "-- $n"; cat "$SCR/$n/run.txt"; }
        done
    } > "$out" 2>&1
}
ALL="x86_64 i386 aarch64 arm riscv64 riscv32 loongarch64 mips ppc s390x"
run_round ported.out "$SCR/orig" $ALL
rec ported "ustart.cc + neutral_tests.cc + F3-18 files (+ port32.cc on 32-bit CPUs)" "$CLANG_VER; $QUSER_VER" \
    "clang++ --target=<cpu> <flags> ...; ld.lld; qemu-<cpu> t" "0" \
    "result:    64-bit CPUs pass; the 32-bit CPUs crash in the formatting test as expected (see ported.out)" \
    "note:      user-mode emulation (qemu-user): the CPU's instructions, Linux system calls; no kernel boots"
for n in x86_64 aarch64 riscv64 loongarch64 s390x; do
    grep -q "^$n .* 10 passed, 0 failed" ported.out || status=1
done
for n in i386 arm riscv32 mips ppc; do
    grep -q "^$n  *ok  *139 " ported.out || status=1
done


# 3. fixed: the 32-bit CPUs with the two fixed files
run_round fixed.out "$SCR/fixed" i386 arm riscv32 mips ppc x86_64 s390x
rec fixed "the same, with .scratch/fixed copies of kformat.h and neutral_tests.cc" "$CLANG_VER; $QUSER_VER" \
    "clang++ --target=<cpu> <flags> ...; ld.lld; qemu-<cpu> t" "0" \
    "note:      x86_64 and s390x are re-run to show the fix changes nothing on 64-bit CPUs"
for n in i386 arm riscv32 mips ppc x86_64 s390x; do
    grep -q "^$n .* 10 passed, 0 failed" fixed.out || status=1
done

# 4. forensic: the crash, seen through qemu-user's system-call trace (unfixed build)
{
    for n in i386 arm riscv32 mips ppc; do
        tgt="$(echo "$TARGETS" | grep "^$n|" | cut -d'|' -f2)"
        fl="$(echo "$TARGETS" | grep "^$n|" | cut -d'|' -f4)"
        port="$(echo "$TARGETS" | grep "^$n|" | cut -d'|' -f5)"
        ubuild "$n" "$tgt" "$fl" "$port" "$SCR/orig" > /dev/null
        echo "== qemu-$n -strace (the signal lines) =="
        ( timeout 20 "qemu-$n" -strace "$SCR/$n/t" 2>&1 ) 2> /dev/null | grep -a -E 'SIGSEGV|uncaught' | sed 's/^[0-9]* //'
    done
    echo "== the line under test (labs/F4-23/neutral_tests.cc) =="
    grep -n -A 1 'ksnprintf(buf, sizeof buf' ../F4-23/neutral_tests.cc
} > forensic.out 2>&1
rec forensic "unfixed 32-bit builds" "$QUSER_VER" "qemu-<cpu> -strace t" "0"
grep -q 'si_addr=0xffffffff' forensic.out && grep -q 'si_addr=0x80000000' forensic.out || status=1

# bash's own "Segmentation fault" job notices are not program output: drop them
sed -i '/run.sh: line [0-9]*: /d; /^ *[0-9]* Done  /d' ported.out forensic.out
rm -rf .scratch
exit $status
