#!/usr/bin/env python3
"""mkvars.py - F11-02 Listing 2: our own Secure Boot keys and the signed variable updates
that put them into the firmware.

    mkvars.py keys                 make keys/{PK,KEK,db1,db2}.{key,crt} if they are missing
    mkvars.py enroll  updates.inc  db = {db1}, KEK = {KEK}, PK = {PK}  (applied in that order)
    mkvars.py rotate  updates.inc  db += {db2} (append), dbx += {db1 certificate}
    mkvars.py replay  updates.inc  the enrolment's db update again, with its old time stamp
    mkvars.py forged  updates.inc  db += {db2}, but signed with the db1 key instead of KEK

Each update is an EFI_VARIABLE_AUTHENTICATION_2 header (a time stamp and a PKCS#7 signature)
followed by an EFI_SIGNATURE_LIST. The signature covers: variable name (UTF-16, no terminator),
vendor GUID, attributes, time stamp, data. PK is signed by PK itself, KEK by PK, db and dbx by
KEK. Layouts, GUIDs and attribute bits are written from memory of the UEFI Specification
(sections "Variable Services" and "Secure Boot and Driver Signing"), pending verification; the
firmware's acceptance or refusal in run.sh is the test. The output is a C++ include file that
setvars.cc compiles in.
"""
import datetime
import os
import struct
import sys
import uuid

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives.serialization import pkcs7
from cryptography.x509.oid import NameOID

GLOBAL = uuid.UUID("8be4df61-93ca-11d2-aa0d-00e098032b8c")      # EFI_GLOBAL_VARIABLE
IMAGE_DB = uuid.UUID("d719b2cb-3d3a-4596-a3bc-dad00e67656f")    # EFI_IMAGE_SECURITY_DATABASE_GUID
CERT_X509 = uuid.UUID("a5c059a1-94e4-4aa7-87b5-ab155c2bf072")   # EFI_CERT_X509_GUID
CERT_PKCS7 = uuid.UUID("4aafd29d-68df-49ee-8aa9-347d375665a7")  # EFI_CERT_TYPE_PKCS7_GUID
OWNER = uuid.UUID("5353f301-0000-4000-8000-000000000301")      # our made-up owner GUID ("SS301")

NV, BS, RT, TIME_AUTH, APPEND = 0x01, 0x02, 0x04, 0x20, 0x40
ATTRS = NV | BS | RT | TIME_AUTH
KEYS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "keys")


def guid_bytes(g):
    return g.bytes_le                     # EFI_GUID: first three fields little-endian


def make_key(name, common_name):
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    subject = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, common_name)])
    start = datetime.datetime(2026, 1, 1, tzinfo=datetime.timezone.utc)
    cert = (x509.CertificateBuilder().subject_name(subject).issuer_name(subject)
            .public_key(key.public_key()).serial_number(x509.random_serial_number())
            .not_valid_before(start).not_valid_after(start + datetime.timedelta(days=3650))
            .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
            .sign(key, hashes.SHA256()))
    with open(os.path.join(KEYS, name + ".key"), "wb") as f:
        f.write(key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                                  serialization.NoEncryption()))
    with open(os.path.join(KEYS, name + ".crt"), "wb") as f:
        f.write(cert.public_bytes(serialization.Encoding.PEM))


def load(name):
    cert = x509.load_pem_x509_certificate(open(os.path.join(KEYS, name + ".crt"), "rb").read())
    key = serialization.load_pem_private_key(open(os.path.join(KEYS, name + ".key"), "rb").read(), None)
    return cert, key


def esl_x509(cert):
    """One EFI_SIGNATURE_LIST holding one X.509 certificate (EFI_SIGNATURE_DATA = owner + cert)."""
    der = cert.public_bytes(serialization.Encoding.DER)
    entry = guid_bytes(OWNER) + der
    return guid_bytes(CERT_X509) + struct.pack("<III", 28 + len(entry), 0, len(entry)) + entry


def efi_time(year, month, day):
    # EFI_TIME: Year, Month, Day, Hour, Minute, Second, Pad1, Nanosecond, TimeZone, Daylight, Pad2
    return struct.pack("<HBBBBBBIhBB", year, month, day, 0, 0, 0, 0, 0, 0, 0, 0)


def auth2(name, vendor, attrs, timestamp, data, signer):
    cert, key = signer
    signed = name.encode("utf-16-le") + guid_bytes(vendor) + struct.pack("<I", attrs) + timestamp + data
    p7 = (pkcs7.PKCS7SignatureBuilder().set_data(signed).add_signer(cert, key, hashes.SHA256())
          .sign(serialization.Encoding.DER,
                [pkcs7.PKCS7Options.DetachedSignature, pkcs7.PKCS7Options.Binary,
                 pkcs7.PKCS7Options.NoAttributes]))
    # WIN_CERTIFICATE_UEFI_GUID: dwLength, wRevision 0x0200, wCertificateType 0x0EF1, CertType GUID
    win = struct.pack("<IHH", 8 + 16 + len(p7), 0x0200, 0x0EF1) + guid_bytes(CERT_PKCS7) + p7
    return timestamp + win + data


def emit(path, updates):
    with open(path, "w") as f:
        f.write("// generated by mkvars.py - signed Secure Boot variable updates, applied in order\n")
        for i, (name, vendor, attrs, blob) in enumerate(updates):
            f.write("constexpr uint8_t kBlob%d[] = {" % i)
            f.write(",".join("0x%02x" % b for b in blob))
            f.write("};\n")
        f.write("constexpr Update kUpdates[] = {\n")
        for i, (name, vendor, attrs, blob) in enumerate(updates):
            g = "efi::kGlobalVariableGuid" if vendor == GLOBAL else "efi::kImageSecurityDatabaseGuid"
            f.write('    {u"%s", &%s, 0x%02x, sizeof kBlob%d, kBlob%d},\n' % (name, g, attrs, i, i))
        f.write("};\n")
    for name, vendor, attrs, blob in updates:
        print("%-4s attributes 0x%02x, %5d bytes (auth header + signature list)" % (name, attrs, len(blob)))


def main():
    os.makedirs(KEYS, exist_ok=True)
    what = sys.argv[1]
    if what == "keys":
        for name, cn in (("PK", "SS301 lab Platform Key"), ("KEK", "SS301 lab Key Exchange Key"),
                         ("db1", "SS301 lab signing key 2026"), ("db2", "SS301 lab signing key 2027")):
            if not os.path.exists(os.path.join(KEYS, name + ".crt")):
                make_key(name, cn)
        return
    pk, kek, db1, db2 = load("PK"), load("KEK"), load("db1"), load("db2")
    if what == "enroll":
        t = efi_time(2026, 1, 1)
        updates = [("db", IMAGE_DB, ATTRS, auth2("db", IMAGE_DB, ATTRS, t, esl_x509(db1[0]), kek)),
                   ("KEK", GLOBAL, ATTRS, auth2("KEK", GLOBAL, ATTRS, t, esl_x509(kek[0]), pk)),
                   ("PK", GLOBAL, ATTRS, auth2("PK", GLOBAL, ATTRS, t, esl_x509(pk[0]), pk))]
    elif what == "rotate":
        t = efi_time(2026, 6, 1)
        updates = [("db", IMAGE_DB, ATTRS | APPEND,
                    auth2("db", IMAGE_DB, ATTRS | APPEND, t, esl_x509(db2[0]), kek)),
                   ("dbx", IMAGE_DB, ATTRS | APPEND,
                    auth2("dbx", IMAGE_DB, ATTRS | APPEND, t, esl_x509(db1[0]), kek))]
    elif what == "replay":
        # the enrolment's db update again: validly signed by KEK, but with the old time stamp
        t = efi_time(2026, 1, 1)
        updates = [("db", IMAGE_DB, ATTRS, auth2("db", IMAGE_DB, ATTRS, t, esl_x509(db1[0]), kek))]
    elif what == "forged":
        # an attacker without the KEK tries to add their own db key, signing with the db1 key
        t = efi_time(2026, 7, 1)
        updates = [("db", IMAGE_DB, ATTRS | APPEND,
                    auth2("db", IMAGE_DB, ATTRS | APPEND, t, esl_x509(db2[0]), db1))]
    else:
        sys.exit("unknown command " + what)
    emit(sys.argv[2], updates)


if __name__ == "__main__":
    main()
