#!/usr/bin/env python3
"""mkconfig.py - F9-67: resolve the robot image's build configuration.

    python3 mkconfig.py robot.config out/.config out/robot_config.h

A miniature of the idea behind the Linux kernel's Kconfig: every option has a type, a default,
an allowed range and a "depends on" rule. The input file sets some options; the tool fills in
the defaults, checks the ranges, and switches off any option whose dependency is off,
printing a line for each one it drops (how Linux's own tools treat such options is discussed,
marked unverified, in F9-67). The options are the course's own, not Linux options.
"""
import sys

# name, type, default, (min, max) or None, depends-on or None
RULES = [
    ("ROBOT_CONTROL_PERIOD_US", "int", 1000, (100, 100000), None),
    ("ROBOT_DEFAULT_CYCLES", "int", 500, (1, 1000000), None),
    ("ROBOT_SAFE_HOLD_CYCLES", "int", 300, (1, 100000), None),
    ("ROBOT_DRIVER_PL061", "bool", "y", None, None),
    ("ROBOT_DRIVER_PL031", "bool", "y", None, None),
    ("ROBOT_RTC_TIMESTAMPS", "bool", "y", None, "ROBOT_DRIVER_PL031"),
    ("ROBOT_ESTOP", "bool", "y", None, "ROBOT_DRIVER_PL061"),
    ("ROBOT_REQUIRE_ESTOP_TO_ARM", "bool", "y", None, None),
]


def read_config(path):
    values = {}
    with open(path) as f:
        for number, line in enumerate(f, 1):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            key, sep, value = line.partition("=")
            if not sep or not key.startswith("CONFIG_"):
                sys.exit("%s:%d: expected CONFIG_NAME=value" % (path, number))
            values[key[len("CONFIG_"):]] = value
    return values


def main():
    if len(sys.argv) != 4:
        sys.exit("usage: mkconfig.py robot.config .config robot_config.h")
    given = read_config(sys.argv[1])
    known = {r[0] for r in RULES}
    errors = ["unknown option CONFIG_%s" % k for k in given if k not in known]
    final = {}
    for name, kind, default, limits, depends in RULES:
        value = given.get(name, default)
        if kind == "int":
            value = int(value)
            if not limits[0] <= value <= limits[1]:
                errors.append("CONFIG_%s=%d outside %d..%d" % (name, value, limits[0], limits[1]))
        elif value not in ("y", "n"):
            errors.append("CONFIG_%s=%s is not y or n" % (name, value))
        if depends and final.get(depends) != "y" and value == "y":
            print("mkconfig: dropped CONFIG_%s=y because it depends on CONFIG_%s, which is n"
                  % (name, depends))
            value = "n"
        final[name] = value
    if errors:
        for e in errors:
            print("mkconfig: error:", e)
        sys.exit(1)
    with open(sys.argv[2], "w") as f:
        for name, value in final.items():
            f.write("CONFIG_%s=%s\n" % (name, value))
    with open(sys.argv[3], "w") as f:
        f.write("// Generated by mkconfig.py from %s - do not edit.\n#pragma once\n" % sys.argv[1])
        for name, value in final.items():
            number = value if isinstance(value, int) else (1 if value == "y" else 0)
            f.write("#define CONFIG_%s %d\n" % (name, number))
    for name, value in final.items():
        print("CONFIG_%s=%s" % (name, value))


if __name__ == "__main__":
    main()
