// robot.cc - F9-67: the course's robot OS image (a bare-metal AArch64 kernel, not Linux).
// Boot stages, each time-stamped from the architectural counter:
//   1. console from /chosen/stdout-path;  2. bind drivers by "compatible" and "status";
//   3. find the e-stop input named by the /robot node;  4. arm (or refuse to);
//   5. run the control loop at a fixed period, polling the e-stop every cycle;
//   6. on e-stop: safe state (actuator command 0), latched until a reset.
// Options come from robot_config.h (generated by mkconfig.py) and from /chosen/bootargs.
#include "fdt.h"
#include "kbase.h"
#include "robot_config.h"

namespace {

struct Board {
    uint64_t uart = 0;
    uint64_t gpio = 0;      // PL061 base, 0 if not bound
    uint64_t rtc = 0;       // PL031 base, 0 if not bound
    int gpio_node = fdt::kNone;
};
Board g_board;

uint64_t now_us() { return k::counter() * 1000000 / k::counter_freq(); }
void stamp(const char* what) { k::printf("[%8lu us] %s\n", now_us(), what); }

// --- drivers. Register offsets: PL011 TRM, PL061 TRM, PL031 TRM (title only, pending
// verification); the runs show QEMU's models behave this way.
void pl011_putc(char c)
{
    while ((k::rd32(g_board.uart + 0x18) & (1u << 5)) != 0) {   // FR.TXFF: transmit FIFO full
    }
    k::wr32(g_board.uart, static_cast<uint8_t>(c));
}
bool probe_pl011(const fdt::Tree&, int, uint64_t) { return true; }   // already the console
bool probe_pl061(const fdt::Tree&, int node, uint64_t base)
{
    if (!CONFIG_ROBOT_DRIVER_PL061) {
        return false;
    }
    k::wr32(base + 0x400, 0);           // GPIODIR: every line an input
    g_board.gpio = base;
    g_board.gpio_node = node;
    return true;
}
bool probe_pl031(const fdt::Tree&, int, uint64_t base)
{
    if (!CONFIG_ROBOT_DRIVER_PL031) {
        return false;
    }
    g_board.rtc = base;
    return true;
}

struct Driver {
    const char* compatible;
    bool (*probe)(const fdt::Tree&, int, uint64_t);
};
const Driver kDrivers[] = {
    {"arm,pl011", probe_pl011},
    {"arm,pl061", probe_pl061},
    {"arm,pl031", probe_pl031},
};

void bind_drivers(const fdt::Tree& t)
{
    char path[96];
    for (int n = t.root(); n != fdt::kNone; n = t.next_node(n)) {
        uint64_t base = 0;
        uint64_t size = 0;
        fdt::Prop c;
        if (!t.prop(n, "compatible", c) || !t.mmio(n, 0, base, size)) {
            continue;                    // not a memory-mapped device
        }
        t.path(n, path, sizeof path);
        if (!t.available(n)) {
            k::printf("  %-22s disabled in the devicetree: skipped\n", path);
            continue;
        }
        const char* result = "no driver in this image";
        for (const Driver& d : kDrivers) {
            if (t.compatible(n, d.compatible)) {
                result = d.probe(t, n, base) ? "bound" : "driver not configured";
                break;
            }
        }
        k::printf("  %-22s %-22s 0x%lx  %s\n", path, reinterpret_cast<const char*>(c.data), base, result);
    }
}

// --- the e-stop input: /robot/estop-gpios = <&gpio line flags>
int find_estop_line(const fdt::Tree& t)
{
    int robot = t.find_path("/robot");
    fdt::Prop p;
    if (!CONFIG_ROBOT_ESTOP || robot == fdt::kNone || !t.prop(robot, "estop-gpios", p) || p.cells() < 2) {
        return -1;
    }
    int controller = t.find_phandle(p.u32(0));
    if (controller == fdt::kNone || controller != g_board.gpio_node) {
        return -1;                       // the controller it names has no bound driver
    }
    return static_cast<int>(p.u32(1));
}
bool estop_pressed(int line)
{
    // GPIODATA: the address bits [9:2] select which lines a read returns; 0x3fc = all eight.
    return (k::rd32(g_board.gpio + 0x3fc) & (1u << line)) != 0;
}

// --- bootargs: "robot.cycles=N" overrides CONFIG_ROBOT_DEFAULT_CYCLES
uint64_t cycles_from_bootargs(const fdt::Tree& t)
{
    uint64_t cycles = CONFIG_ROBOT_DEFAULT_CYCLES;
    int chosen = t.find_path("/chosen");
    fdt::Prop p;
    if (chosen == fdt::kNone || !t.prop(chosen, "bootargs", p)) {
        return cycles;
    }
    const char* s = reinterpret_cast<const char*>(p.data);
    k::printf("bootargs: \"%s\"\n", s);
    const char key[] = "robot.cycles=";
    for (uint32_t i = 0; s[i] != '\0'; ++i) {
        uint32_t j = 0;
        while (key[j] != '\0' && s[i + j] == key[j]) {
            ++j;
        }
        if (key[j] == '\0') {
            cycles = 0;
            for (uint32_t m = i + j; s[m] >= '0' && s[m] <= '9'; ++m) {
                cycles = cycles * 10 + static_cast<uint64_t>(s[m] - '0');
            }
        }
    }
    return cycles;
}

// --- the actuator: in this image a variable; on a robot, a motor driver's command register
int64_t g_actuator = 0;
void command(int64_t value) { g_actuator = value; }

}  // namespace

extern "C" void kmain(const void* dtb, uint64_t, uint64_t)
{
    fdt::Tree t;
    if (!t.init(dtb)) {
        k::exit(2);
    }
    int chosen = t.find_path("/chosen");
    fdt::Prop sp;
    int con = fdt::kNone;
    if (chosen != fdt::kNone && t.prop(chosen, "stdout-path", sp)) {
        con = t.find_path(reinterpret_cast<const char*>(sp.data));
    }
    uint64_t size = 0;
    if (con == fdt::kNone || !t.available(con) || !t.mmio(con, 0, g_board.uart, size)) {
        k::exit(4);                      // no console: only the exit code can tell
    }
    k::set_console(pl011_putc);
    stamp("console up (stage 1)");
    fdt::Prop model;
    if (t.prop(t.root(), "model", model)) {
        k::printf("model: %s\n", reinterpret_cast<const char*>(model.data));
    }
    k::printf("time base: architectural counter at %lu Hz (CNTFRQ_EL0), counting since reset\n",
              k::counter_freq());
    k::printf("image options: period %u us, safe hold %u cycles, e-stop %s, require e-stop to arm %s\n",
              CONFIG_ROBOT_CONTROL_PERIOD_US, CONFIG_ROBOT_SAFE_HOLD_CYCLES,
              CONFIG_ROBOT_ESTOP ? "y" : "n", CONFIG_ROBOT_REQUIRE_ESTOP_TO_ARM ? "y" : "n");
    bind_drivers(t);
    stamp("drivers bound (stage 2)");
    if (CONFIG_ROBOT_RTC_TIMESTAMPS && g_board.rtc != 0) {
        k::printf("wall clock from the RTC: %u s since 1970\n", k::rd32(g_board.rtc));
    }
    int estop = find_estop_line(t);
    if (estop >= 0) {
        k::printf("e-stop: GPIO line %d, now %s\n", estop, estop_pressed(estop) ? "PRESSED" : "released");
    } else {
        k::printf("e-stop: no usable input\n");
    }
    stamp("e-stop resolved (stage 3)");
    if (estop < 0 && CONFIG_ROBOT_REQUIRE_ESTOP_TO_ARM) {
        k::printf("REFUSING TO ARM: no e-stop input; actuators stay at 0\n");
        k::exit(6);
    }
    uint64_t cycles = cycles_from_bootargs(t);
    stamp("ARMED: control loop starts (stage 4)");

    const uint64_t period = CONFIG_ROBOT_CONTROL_PERIOD_US * k::counter_freq() / 1000000;
    uint64_t next = k::counter() + period;
    uint64_t max_late = 0;
    uint64_t late_over_period = 0;
    uint64_t estop_cycle = 0;
    bool safe = false;
    uint64_t nonzero_in_safe = 0;
    uint64_t c = 0;
    for (; c < cycles; ++c) {
        uint64_t now = k::counter();
        while (now < next) {             // wait for the absolute release time of this cycle
            now = k::counter();
        }
        uint64_t late = now - next;
        max_late = late > max_late ? late : max_late;
        late_over_period += late > period ? 1 : 0;
        next += period;
        bool pressed = estop >= 0 && estop_pressed(estop);
        if (pressed && !safe) {
            safe = true;                 // latched: only a reset clears it
            estop_cycle = c;
            command(0);
            k::printf("[%8lu us] E-STOP at cycle %lu: SAFE STATE, actuator command 0 (latched)\n",
                      now_us(), c);
        }
        if (safe) {
            command(0);
            nonzero_in_safe += g_actuator != 0 ? 1 : 0;
            if (c - estop_cycle == CONFIG_ROBOT_SAFE_HOLD_CYCLES) {
                k::printf("e-stop input now %s; still SAFE after %u cycles (latched until reset)\n",
                          pressed ? "PRESSED" : "released", CONFIG_ROBOT_SAFE_HOLD_CYCLES);
                ++c;
                break;
            }
        } else {
            command(static_cast<int64_t>(c % 200) - 100);   // a test pattern, -100..99
        }
    }
    const uint64_t f = k::counter_freq();
    k::printf("[%8lu us] loop ended after %lu cycles; worst lateness %lu us; cycles later than one period: %lu\n",
              now_us(), c, max_late * 1000000 / f, late_over_period);
    if (safe) {
        k::printf("safe-state check: %lu non-zero actuator commands after the e-stop (expected 0)\n",
                  nonzero_in_safe);
        k::exit(nonzero_in_safe == 0 ? 0 : 7);
    }
    k::printf("F9-67 image ok\n");
    k::exit(0);
}
