// F1-65 forensic evidence generator: "The jumpy IMU".
// SYNTHETIC data, generated by this program (no real robot or IMU was used):
// the z-axis accelerometer of a pretend robot, logged at a pretend 1000 samples
// per second for 1 s with the drive motors off and 1 s with them on. While the
// motors run, a vibration (87 Hz plus a weaker 174 Hz harmonic) is added. The
// learner gets only jumpy_imu.csv and this summary; how it was made is in the key.
#include "uimu_model.h"

#include <cmath>
#include <cstdio>
#include <numbers>
#include <vector>

struct Stats
{
    double mean, sd, lo, hi;
};

Stats stats(const std::vector<double>& v)
{
    double m = 0.0;
    double lo = v[0];
    double hi = v[0];
    for (double x : v) {
        m += x;
        lo = x < lo ? x : lo;
        hi = x > hi ? x : hi;
    }
    m /= static_cast<double>(v.size());
    double s = 0.0;
    for (double x : v) {
        s += (x - m) * (x - m);
    }
    return {m, std::sqrt(s / static_cast<double>(v.size() - 1)), lo, hi};
}

int main()
{
    const int n = 1000;
    const double fs = 1000.0;
    Noise noise(2026u);
    std::vector<double> off(n);
    std::vector<double> on(n);
    for (int k = 0; k < n; ++k) {
        const double t = k / fs;
        off[k] = 1.0 + noise.gaussian(0.01);
        on[k] = 1.0 + noise.gaussian(0.01) + 0.30 * std::sin(2.0 * std::numbers::pi * 87.0 * t)
                + 0.08 * std::sin(2.0 * std::numbers::pi * 174.0 * t + 1.0);
    }
    std::FILE* f = std::fopen("jumpy_imu.csv", "w");
    if (f == nullptr) {
        std::printf("cannot write jumpy_imu.csv\n");
        return 1;
    }
    std::fprintf(f, "t_s,az_motors_off_g,az_motors_on_g\n");
    for (int k = 0; k < n; ++k) {
        std::fprintf(f, "%.3f,%.5f,%.5f\n", k / fs, off[k], on[k]);
    }
    std::fclose(f);

    std::printf("wrote jumpy_imu.csv: %d rows, fs = %.0f Hz\n\n", n, fs);
    std::printf("first 12 rows:\n t_s    off_g     on_g\n");
    for (int k = 0; k < 12; ++k) {
        std::printf("%.3f  %.4f  %+.4f\n", k / fs, off[k], on[k]);
    }
    const Stats a = stats(off);
    const Stats b = stats(on);
    std::printf("\n%-11s %8s %8s %8s %8s\n", "column", "mean g", "sd g", "min g", "max g");
    std::printf("%-11s %8.4f %8.4f %8.4f %8.4f\n", "motors off", a.mean, a.sd, a.lo, a.hi);
    std::printf("%-11s %8.4f %8.4f %8.4f %8.4f\n", "motors on", b.mean, b.sd, b.lo, b.hi);
    return 0;
}
