#!/usr/bin/env python3
"""gen_dialect.py - F10-30 Listing 2: turn a dialect XML file into a C++ header.

For every message it computes
  * the WIRE ORDER of the fields: the fields before <extensions/> sorted by the size of
    their base type, largest first (stable, so equal sizes keep their declared order),
    followed by the extension fields in declared order;
  * the payload length without and with extensions;
  * the CRC "extra" byte: a CRC-16 over the message name and, for each non-extension field
    in wire order, its base type, its name and (for arrays) its length; the low and high
    bytes are XORed into one byte. Sender and receiver mix this byte into every frame's
    checksum, so two programs built from DIFFERENT definitions of a message reject each
    other's frames.
These rules are the ones the university's U-link uses. They are modelled on the MAVLink
serialization rules as the chapter recalls them; check them against the MAVLink Developer
Guide before relying on them for real MAVLink (see the chapter's unverified box).

usage: gen_dialect.py <dialect.xml> <output.h> [C++ namespace, default udialect]
"""
import sys
import xml.etree.ElementTree as ET

SIZES = {"uint8_t": 1, "int8_t": 1, "char": 1, "uint16_t": 2, "int16_t": 2,
         "uint32_t": 4, "int32_t": 4, "float": 4, "uint64_t": 8, "int64_t": 8, "double": 8}


def crc_accumulate(byte, crc):
    """CRC-16/MCRF4XX step (polynomial 0x1021, reflected, initial value 0xFFFF)."""
    tmp = byte ^ (crc & 0xFF)
    tmp = (tmp ^ (tmp << 4)) & 0xFF
    return ((crc >> 8) ^ (tmp << 8) ^ (tmp << 3) ^ (tmp >> 4)) & 0xFFFF


def crc_bytes(data, crc=0xFFFF):
    for b in data:
        crc = crc_accumulate(b, crc)
    return crc


class Field:
    def __init__(self, elem, extension):
        t = elem.get("type")
        self.array = 0
        if "[" in t:
            t, n = t.split("[")
            self.array = int(n.rstrip("]"))
        self.base = t
        self.name = elem.get("name")
        self.extension = extension
        self.size = SIZES[t] * max(1, self.array)


def camel(name):
    return "".join(part.capitalize() for part in name.lower().split("_"))


def parse(path):
    messages = []
    for m in ET.parse(path).getroot().iter("message"):
        fields, ext = [], False
        for child in m:
            if child.tag == "extensions":
                ext = True
            elif child.tag == "field":
                fields.append(Field(child, ext))
        base = [f for f in fields if not f.extension]
        wire = sorted(base, key=lambda f: -SIZES[f.base]) + [f for f in fields if f.extension]
        crc = crc_bytes((m.get("name") + " ").encode())
        for f in wire:
            if f.extension:
                continue
            crc = crc_bytes((f.base + " ").encode(), crc)
            crc = crc_bytes((f.name + " ").encode(), crc)
            if f.array:
                crc = crc_accumulate(f.array, crc)
        messages.append({
            "id": int(m.get("id")), "name": m.get("name"), "wire": wire,
            "min_len": sum(f.size for f in base), "len": sum(f.size for f in wire),
            "crc_extra": (crc & 0xFF) ^ (crc >> 8),
        })
    return messages


def cpp_type(f):
    base = "std::" + f.base if f.base.endswith("_t") else f.base
    return f"std::array<{base}, {f.array}>" if f.array else base


def emit(messages, src, namespace):
    o = [f"// GENERATED by gen_dialect.py from {src}. Do not edit.",
         "#pragma once", "#include <array>", "#include <cstddef>", "#include <cstdint>",
         "#include <cstring>", "", f"namespace {namespace} {{", "",
         "struct MsgInfo { std::uint32_t id; const char* name; std::uint8_t crcExtra;",
         "                 std::uint8_t minLen; std::uint8_t len; };", ""]
    for m in messages:
        o.append(f"struct {camel(m['name'])} {{")
        o.append(f"    static constexpr std::uint32_t kId = {m['id']};")
        o.append(f"    static constexpr std::uint8_t kCrcExtra = {m['crc_extra']};")
        o.append(f"    static constexpr std::uint8_t kLen = {m['len']};")
        for f in m["wire"]:
            o.append(f"    {cpp_type(f)} {f.name}{{}};")
        o.append("    // write the payload in wire order; returns its full length")
        o.append("    std::size_t pack(std::uint8_t* p) const")
        o.append("    {")
        off = 0
        for f in m["wire"]:
            o.append(f"        std::memcpy(p + {off}, &{f.name}, {f.size});")
            off += f.size
        o.append("        return kLen;")
        o.append("    }")
        o.append("    // read a payload; bytes beyond n (truncated trailing zeros) count as zero")
        o.append("    static " + camel(m["name"]) + " unpack(const std::uint8_t* p, std::size_t n)")
        o.append("    {")
        o.append("        std::uint8_t full[kLen] = {};")
        o.append("        std::memcpy(full, p, n < kLen ? n : kLen);")
        o.append(f"        {camel(m['name'])} m;")
        off = 0
        for f in m["wire"]:
            o.append(f"        std::memcpy(&m.{f.name}, full + {off}, {f.size});")
            off += f.size
        o.append("        return m;")
        o.append("    }")
        o.append("};")
        o.append("")
    o.append(f"inline constexpr std::array<MsgInfo, {len(messages)}> kMessages{{{{")
    for m in messages:
        o.append(f"    {{{m['id']}, \"{m['name']}\", {m['crc_extra']}, {m['min_len']}, {m['len']}}},")
    o += ["}};", "", "inline const MsgInfo* find(std::uint32_t id)", "{",
          "    for (const MsgInfo& i : kMessages) {", "        if (i.id == id) {",
          "            return &i;", "        }", "    }", "    return nullptr;", "}", "",
          f"}}  // namespace {namespace}", ""]
    return "\n".join(o)


def main(xml_path, out_path, namespace="udialect"):
    messages = parse(xml_path)
    print(f"{xml_path}: {len(messages)} messages")
    print(f"{'id':>3}  {'name':18} {'len':>3} {'min':>3}  crc_extra  wire order")
    for m in messages:
        order = " ".join(f.name + ("[%d]" % f.array if f.array else "") + ("*" if f.extension else "")
                         for f in m["wire"])
        print(f"{m['id']:>3}  {m['name']:18} {m['len']:>3} {m['min_len']:>3}  {m['crc_extra']:>9}  {order}")
    print("(* = extension field: appended in declared order, not part of crc_extra)")
    print(f"CRC-16/MCRF4XX of the ASCII test string 123456789: 0x{crc_bytes(b'123456789'):04X}")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(emit(messages, xml_path.split("/")[-1], namespace))
    print("header written:", out_path.split("/")[-1])


if __name__ == "__main__":
    if len(sys.argv) not in (3, 4):
        sys.exit(__doc__)
    main(*sys.argv[1:])
