build exit code: 0
   text	   data	    bss	    dec	    hex	filename
  30182	   7816	  17184	  55182	   d78e	k.elf
driver descriptors in the image (section dr403_drivers -> .drivers):
  bcm2835gpio_driver
  fixedclk_driver
  fwcfg_driver
  gic_driver
  pl011_driver
  pl031_driver
  pl061_driver
  psci_driver
  timer_driver
  virtio_driver
