#!/usr/bin/env bash
# F8-03 extra lab steps:
#   pingpong        - Listing 2: alpha and beta between 2 MPI processes (shared memory, one machine)
#   allreduce_bench - Listing 3: predict with that alpha and beta, then measure MPI_Allreduce
#                     on 4 processes with Open MPI's ring algorithm forced
#   forensic        - Listing 1 (the model) for the forensic scenario: 8 KiB and 256 MiB
#                     all-reduce on N = 2, 4, 8, 16 ranks of the invented TN-1 links
# Measurement builds use -O2 without sanitizers (sanitizers change timing). MPI notes as in
# F8-01/run.sh (--allow-run-as-root, --oversubscribe, -DOMPI_SKIP_MPICXX).
set -u
cd "$(dirname "$0")"
status=0
GXX="$(g++ --version | head -n 1)"
MPV="$(mpirun --version 2>&1 | head -n 1)"
MACHINE="$(uname -s) $(uname -m) (cloud build container, $(nproc) logical CPUs shared with other jobs; MPI processes on one machine, no GPU)"
RUN="mpirun --allow-run-as-root --oversubscribe"
FLAGS="-std=c++20 -O2 -Wall -Wextra -Wpedantic -Werror -DOMPI_SKIP_MPICXX"

header() {  # header <name> <listing> <toolchain> <command>
    {
        echo "listing:   $2"
        echo "toolchain: $3"
        echo "command:   $4"
        echo "date:      $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "machine:   $MACHINE"
    } > "$1.log"
}
build() {  # build <name>; returns non-zero on failure (and records it)
    if ! mpic++ $FLAGS "$1.cc" -o ".bin_F803_$1" > ".build_$1.txt" 2>&1; then
        echo "result:    BUILD FAILED" >> "$1.log"; cat ".build_$1.txt" >> "$1.log"
        rm -f ".build_$1.txt"; status=1; return 1
    fi
    rm -f ".build_$1.txt"
}

# --- pingpong
header pingpong "pingpong.cc" "$MPV; $GXX" "mpic++ $FLAGS pingpong.cc -o pingpong; timeout 120 $RUN -np 2 ./pingpong"
alpha=1; beta=1
if build pingpong; then
    timeout 120 $RUN -np 2 ./.bin_F803_pingpong > pingpong.out 2>&1; rc=$?
    echo "exit code: $rc" >> pingpong.log; [ "$rc" = 0 ] || status=1
    read -r alpha beta < <(grep '^fit:' pingpong.out | awk '{print $2, $3}')
fi

# --- allreduce_bench
header allreduce_bench "allreduce_bench.cc" "$MPV; $GXX" \
  "mpic++ $FLAGS allreduce_bench.cc -o allreduce_bench; timeout 300 $RUN -np 4 --mca coll_tuned_use_dynamic_rules 1 --mca coll_tuned_allreduce_algorithm 4 ./allreduce_bench $alpha $beta   (alpha, beta: the 'fit:' line of pingpong.out)"
if build allreduce_bench; then
    timeout 300 $RUN -np 4 --mca coll_tuned_use_dynamic_rules 1 --mca coll_tuned_allreduce_algorithm 4 \
        ./.bin_F803_allreduce_bench "$alpha" "$beta" > allreduce_bench.out 2>&1; rc=$?
    echo "exit code: $rc" >> allreduce_bench.log; [ "$rc" = 0 ] || status=1
fi
pkill -9 -f "[.]bin_F803_" 2>/dev/null
rm -f .bin_F803_pingpong .bin_F803_allreduce_bench

# --- forensic: the model, run for each N
header forensic "ab_model.cpp (inputs generated by this script)" "$GXX" \
  "g++ -std=c++20 -Wall -Wextra -Wpedantic -Werror -g -fsanitize=address,undefined ab_model.cpp -o ab_model; for N in 2 4 8 16: printf 'N 10 25 TN-1 8192 268435456' | ./ab_model"
if g++ -std=c++20 -Wall -Wextra -Wpedantic -Werror -g -fsanitize=address,undefined ab_model.cpp -o .bin_F803_model; then
    : > forensic.out
    frc=0
    for N in 2 4 8 16; do
        printf '%s 10 25 TN-1_GPU_link_(invented_teaching_values)\n8192\n268435456\n' "$N" \
            | ./.bin_F803_model | grep -vE '^ring (busbw|faster)' >> forensic.out || frc=1
    done
    echo "exit code: $frc" >> forensic.log; [ "$frc" = 0 ] || status=1
else
    echo "result:    BUILD FAILED" >> forensic.log; status=1
fi
rm -f .bin_F803_model
exit $status
