// F1-70 forensic evidence generator: "The bridge that gets hot at standstill".
// One half-bridge leg (high switch H, low switch L) switching at a pretend 20 kHz.
// The controller's gate commands are complementary. Each switch turns ON 20 ns after
// its command rises and turns OFF 60 ns after its command falls (pretend delays).
// Logs the switch states every 10 ns around one transition, plus a count of the time
// both switches conduct together. Synthetic: generated by this model, not measured.
#include <cstdio>
#include <initializer_list>

struct Leg
{
    long onDelay = 2;   // in 10 ns steps
    long offDelay = 6;
};

// Is a switch conducting at step k, given the time its command rose and fell?
bool conducting(long k, long rise, long fall, const Leg& d)
{
    return k >= rise + d.onDelay && k < fall + d.offDelay;
}

void simulate(long deadSteps, bool printTrace)
{
    const Leg d;
    const long period = 5000;  // 50 us = 20 kHz, in 10 ns steps
    const long half = period / 2;
    long overlap = 0;
    // H command: high from 0 to half; L command: high from half+dead to period-dead.
    // The extra terms are the neighbouring periods, whose switches may still be on.
    for (long k = 0; k < period; ++k) {
        const bool h = conducting(k, 0, half, d) || conducting(k, period, period + half, d)
                       || conducting(k, -period, -half, d);
        const bool l = conducting(k, half + deadSteps, period - deadSteps, d)
                       || conducting(k, half + deadSteps - period, -deadSteps, d);
        if (h && l) {
            ++overlap;
        }
        if (printTrace && k >= half - 2 && k <= half + 12) {
            std::printf("  t=%6.2f us  cmdH=%d cmdL=%d   H=%s L=%s%s\n", k * 0.01,
                        k < half ? 1 : 0, (k >= half + deadSteps && k < period - deadSteps) ? 1 : 0,
                        h ? "ON " : "off", l ? "ON " : "off", (h && l) ? "  <== both ON" : "");
        }
    }
    std::printf("  dead time %3ld ns: both switches ON for %ld ns per PWM period\n\n",
                deadSteps * 10, overlap * 10);
}

int main()
{
    std::printf("Evidence 1: trace around the H-off / L-on transition, firmware as shipped\n");
    simulate(0, true);
    std::printf("Evidence 2: same leg, other dead-time settings tried on the bench model\n");
    for (long dead : {2L, 4L, 6L, 10L}) {
        simulate(dead, false);
    }
    return 0;
}
